# Generated by Django 5.0.3 on 2024-08-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
